---
title: "Supercell for COVID cytof"
author: "Belinda Phipson"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Library

```{r}
library(Seurat)
library(SuperCell)
library(limma)
library(edgeR)
library(patchwork)
set.seed(10)
```

# Reading the data into R


```{r}
cytof <- read.csv("C:/Users/phipson.b/OneDrive - wehi.edu.au/Documents/Presentations/Conferences/OzSingleCellHackathon/hackathon_ch3/cell.dat.csv")
```

```{r}
names(cytof)
```

```{r}
keep.col <- grep("asinh",colnames(cytof))
```

```{r}
dat <- t(cytof[,keep.col])
```

```{r}
table(cytof$Sample)
table(cytof$Group)
```

```{r}
CellID <- paste("Cell",1:ncol(dat),sep="")
targets <- data.frame(CellID,Sample=cytof$Sample,Group=cytof$Group,
                      Celltype_L1=cytof$Population.L1, 
                      Celltype_L2=cytof$Population.L2)
```

```{r}
healthy <- dat[,targets$Group=="Healthy"]
colnames(healthy) <- as.character(targets$CellID[targets$Group=="Healthy"])

mild <- dat[,targets$Group=="COVID-Mild"]
colnames(mild) <- as.character(targets$CellID[targets$Group=="COVID-Mild"])

recovered <- dat[,targets$Group=="COVID-Recovered"]
colnames(recovered) <- as.character(targets$CellID[targets$Group=="COVID-Recovered"])

severe <- dat[,targets$Group=="COVID-Severe"]
colnames(severe) <- as.character(targets$CellID[targets$Group=="COVID-Severe"])
```

# Run supercell

```{r}
sc <- SCimplify(as.matrix(healthy),
                k.knn = 5,
                gamma = 20, 
                n.var.genes = nrow(healthy),
                do.scale = FALSE,
                n.pc=10,
                fast.pca = FALSE)
```


```{r}
sc.mild <- SCimplify(as.matrix(mild),
                k.knn = 5,
                gamma = 20, 
                n.var.genes = nrow(mild),
                do.scale = FALSE,
                n.pc=10,
                fast.pca = FALSE)
```

```{r}
sc.recovered <- SCimplify(as.matrix(recovered),
                k.knn = 5,
                gamma = 20, 
                n.var.genes = nrow(recovered),
                do.scale = FALSE,
                n.pc=10,
                fast.pca = FALSE)
```

```{r}
sc.severe <- SCimplify(as.matrix(severe),
                k.knn = 5,
                gamma = 20, 
                n.var.genes = nrow(severe),
                do.scale = FALSE,
                n.pc=10,
                fast.pca = FALSE)
```

```{r}
supercell_plot(sc$graph.supercells, # network
               color.use = "gray", # color of the nodes
               main = paste("Metacell network, Healthy"), 
               seed = 1) 
```

```{r}
supercell_plot(sc.mild$graph.supercells, # network
               color.use = "gray", # color of the nodes
               main = paste("Metacell network, Mild"), 
               seed = 1) 
```
```{r}
supercell_plot(sc.recovered$graph.supercells, # network
               color.use = "gray", # color of the nodes
               main = paste("Metacell network, recovered"), 
               seed = 1) 
```
```{r}
supercell_plot(sc.severe$graph.supercells, # network
               color.use = "gray", # color of the nodes
               main = paste("Metacell network, severe"), 
               seed = 1) 
```

```{r}
sc$broad <- supercell_assign(clusters = targets$Celltype_L1[targets$Group=="Healthy"], 
                                 supercell_membership = sc$membership, # single-cell assignment to metacells
                                 method = "jaccard")
```

```{r}
sc.mild$broad <- supercell_assign(clusters = targets$Celltype_L1[targets$Group=="COVID-Mild"], 
                                 supercell_membership = sc.mild$membership, # single-cell assignment to metacells
                                 method = "jaccard")
```

```{r}
sc.recovered$broad <- supercell_assign(clusters = targets$Celltype_L1[targets$Group=="COVID-Recovered"], 
                                 supercell_membership = sc.recovered$membership, # single-cell assignment to metacells
                                 method = "jaccard")
```

```{r}
sc.severe$broad <- supercell_assign(clusters = targets$Celltype_L1[targets$Group=="COVID-Severe"], 
                                 supercell_membership = sc.severe$membership, # single-cell assignment to metacells
                                 method = "jaccard")
```


```{r}
sc$fine <- supercell_assign(clusters = targets$Celltype_L2[targets$Group=="Healthy"], 
                                 supercell_membership = sc$membership, # single-cell assignment to metacells
                                 method = "jaccard")
```



```{r}
supercell_plot(sc$graph.supercells, 
               group = sc$broad, 
               seed = 10, 
               main = "Metacells colored by cell type assignment: Healthy")
```

```{r}
supercell_plot(sc.mild$graph.supercells, 
               group = sc.mild$broad, 
              seed = 10, 
              main = "Metacells colored by cell type assignment: Mild")
```

```{r}
supercell_plot(sc.recovered$graph.supercells, 
               group = sc.recovered$broad, 
              seed = 10, 
              main = "Metacells colored by cell type assignment: recovered")
```

```{r}
supercell_plot(sc.severe$graph.supercells, 
               group = sc.severe$broad, 
              seed = 10, 
              main = "Metacells colored by cell type assignment: severe")
```


```{r}
purity <- supercell_purity(clusters = targets$Celltype_L1[targets$Group=="Healthy"], 
                           supercell_membership = sc$membership, method = 'max_proportion')

hist(purity)
```

```{r}
purity <- supercell_purity(clusters = targets$Celltype_L2[targets$Group=="Healthy"], 
                           supercell_membership = sc$membership, method = 'max_proportion')

hist(purity)
```

```{r}
SC.GE <- supercell_GE(healthy, sc$membership, mode="average")
```

```{r}
seu <- supercell_2_Seurat(SC.GE,sc,fields = c("broad", "fine"))
```

```{r}
seu <- RunUMAP(seu, dims=1:10)
```

```{r}
DimPlot(seu, reduction = "umap", group.by = "broad", pt.size = 2)
```

```{r}
DimPlot(seu, reduction = "umap", group.by = "fine", pt.size = 2)
```




 