---
title: "Supercell for Cytof"
author: "Belinda Phipson"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

# Library

```{r}
library(Seurat)
library(SuperCell)
library(limma)
library(edgeR)
library(patchwork)
set.seed(10)
```

# Reading the data into R

The cytof data is raw.

The data is mass cytometry based. 

```{r}
cytof <- read.csv("C:/Users/phipson.b/OneDrive - wehi.edu.au/Documents/Presentations/Conferences/OzSingleCellHackathon/hackathon_ch3/CyTOF_WB_BM.csv")
```
 
1 = blood
2 = bone marrow

```{r}
colnames(cytof) <- gsub(".*_","",colnames(cytof))
tissue <- cytof$SampleID
```

```{r}
counts <- t(cytof[,-1])
```

```{r}
transf.counts <- asinh(counts/15)
```

# Run SuperCell on blood

```{r}
#samples <- sample(1:ncol(transf.counts),size=50000)
sc <- SCimplify(transf.counts[,tissue==1],
                k.knn = 5,
                gamma = 20, 
                n.var.genes = nrow(transf.counts),
                do.scale = FALSE)
```

```{r}
#supercell_plot(sc$graph.supercells, # network
#               color.use = "gray", # color of the nodes
#               main = paste("Metacell network, gamma =20"), 
#               seed = 1) 
```


```{r}
SC.GE <- supercell_GE(transf.counts[,tissue==1], sc$membership, mode="average")
```


```{r}
seu <- supercell_2_Seurat(SC.GE,sc)
```

```{r}
seu <- RunUMAP(seu, dims=1:10)
```

```{r}
saveRDS(seu, file="./blood_supercell.Rds")
```


# Run SuperCell on bone marrow

```{r}
#samples <- sample(1:ncol(transf.counts),size=50000)
sc.bm <- SCimplify(transf.counts[,tissue==2],
                k.knn = 5,
                gamma = 20, 
                n.var.genes = nrow(transf.counts),
                do.scale = FALSE)
```

```{r}
#supercell_plot(sc$graph.supercells, # network
#               color.use = "gray", # color of the nodes
#               main = paste("Metacell network, gamma =20"), 
#               seed = 1) 
```


```{r}
SC.GE.bm <- supercell_GE(transf.counts[,tissue==2], sc.bm$membership, mode="average")
```


```{r}
seu.bm <- supercell_2_Seurat(SC.GE.bm,sc.bm)
```

```{r}
seu.bm <- RunUMAP(seu.bm, dims=1:10)
```

```{r}
saveRDS(seu.bm, file="./bm_supercell.Rds")
```
